### PR TITLE
#459 Add breadcrumb for how-to page

### PR DESCRIPTION
**Pull request by kopecms**
Just want some feedback. If it is ok I would add breadcrumb for all pages and also links for higher levels (?)

### CODE REVIEW

**Comment by davehakkens** [comment]
Sounds good! However at the moment only really makes sense on the how-to pages, since they go a layer deeper.

**Comment by kopecms** [comment]
Ok so: breadcrumb for how-to and discussions (I removed displaying a description defined in PageList.tsx), Link to higher level.
Closes #459

**Comment by davehakkens** [comment]
cool. we review pull requests on Tuesday, also don't forget to check the monthly news 👊

**Comment by BenGamma** [comment]
And dave is talking about the monthly news because we mentionned you in it 🤗

**Pull request merged**
