### PR TITLE
#359 func total discussion responses

### PR DESCRIPTION
**Pull request by chupakabra**

### CODE REVIEW

**Comment by chrismclarke** [comment]
Thanks, I will aim to review this by Tuesday

**Comment by chrismclarke** [comment]
Apologies, reached the end of the day without finding a spare moment but will put it as a top priority for tomorrow

**Comment by chrismclarke** [comment]
Note, I've added a placeholder `syncCommentsCount` function for now so that the master build still works (otherwise, because it does not appear in the master branch yet it asks firebase whether it should be removed from the server on each build, and the build fails because you cannot type Y/N during the CI process)

**Comment by chrismclarke** [comment]
actually I've just merged it in for now as adding a placeholder was just awkward and we will still want to keep this code to verify (and can add another bit of code to increment the counter)

**Comment by chupakabra** [comment]
@chrismclarke, sorry, read your comments with some delay

**Comment by BenGamma** [comment]
is this closing #232 ?

**Comment by chrismclarke** [comment]
Sorry for the slow response. I don't think the change was intentional (possibly just whilst testing), no I think you're right that it makes more sense to call from trigger. yes I think simple increment/decrement function would be ideal for the near-future

**Pull request merged**
