### PR TITLE
HowToList component styling

### PR DESCRIPTION
**Pull request by charleenfei**
this is just a simple PR containing style changes for the HowToList component.

I also refactored a bit the way the component is rendered to make it easier to work with in future changes.

The followup PR will contain the changes for the HowTo.content.tsx component as indicated by the new UI styles brief.

### CODE REVIEW

**Comment by BenGamma** [comment]
Hey Charly,
I was probably not clear on the mockups but don't remove the "create how-to" button for now, it's still needed.
Here the main focus is the card display and the card grid.

**Comment by charleenfei** [comment]
> Hey charly, thanks for the PR, a couple quick things:
> 
> 1. I see you've removed the 'ClampLines' component. This was originally designed to ensure that all descriptions fill the same number of lines no matter how long (displaying a '...' if the description is too long). Is there a reason to remove (do you have a better implementation in mind?)

Gotcha, I overlooked that it was being used for this, I can move it back.

> 2. I'm happy to see the styles and render methods moved out to make it easier to work with (👍 ). In the future we would likely want to move it out of the file entirely to implement styled components instead (however no need to worry too much for now, just to make you aware).

noted!

> 3. I see the new font. I'm not sure if we've had full spec from Mattia for exactly what fonts he wants in the project (you probably know more than me at this point), however for now I suggest fine to leave in and will open discussion in a separate git issue. Although would you mind trying to see how easy it would be to import into the build instead of linking? By having it part of the bundle we are not reliant on external servers, improving any future offline build we might want and also avoid flash-of-invisible-text if server slow (I assume at least). Example here:
>    https://stackoverflow.com/questions/41676054/how-to-add-fonts-to-create-react-app-based-projects

Yep, will try to have it imported into the build.

**Comment by charleenfei** [comment]
> Hey Charly,
> I was probably not clear on the mockups but don't remove the "create how-to" button for now, it's still needed.
> Here the main focus is the card display and the card grid.

will put it back in! like you said, in the mockups the button was no longer there (I had just assumed it would be part of the top bar component).

**Comment by charleenfei** [comment]
> 1. I see you've removed the 'ClampLines' component. This was originally designed to ensure that all descriptions fill the same number of lines no matter how long (displaying a '...' if the description is too long). Is there a reason to remove (do you have a better implementation in mind?)

I've just checked again the reasoning for this -- it's because the description in the how-to list has been removed in the new design files.

**Comment by BenGamma** [comment]
Hello here !
I just review the PR and I'm gonna close for now, as I saw it was still a work in progress.
You can still add commits to it but please reopen when you think that it will close the issue #234  ! Thanks 🙌

**Pull request closed without merging**
