### PR TITLE
Module/266 automated tests static analysis

### PR DESCRIPTION
**Pull request by rudolphfunk**
## Background
In response to #266, starting implementation of Automated Testing strategy inline with the 'Testing trophy':

testing trophy

Static Analysis is the foundation. Unit tests are fast and cheap. Integration tests are the best balance of confidence and speed.

## Reasoning
- Linting makes more sense when run before committing your code. By doing so you can ensure no errors go into the repository and enforce code style. [Prettier](https://prettier.io/) config file is already in project, but it is not a dependency. [eslint](https://eslint.org/) and [tslint] (https://palantir.github.io/tslint/) are dependencies and configured. These relying on contributors having their code editors configured correctly to use these formatter and linters, which can be unpredictable and can result in bad habits creeping into the project.
- running a lint process on a whole project is slow and linting results can be irrelevant. Ultimately you only want to lint files that are to be committed. Therefore [lint-staged](https://github.com/okonet/lint-staged) has been introduced to the project. [Husky](https://github.com/typicode/husky) handles the pre-commit hook.
- defaultSeverity has been raised to error in tslint.json to prevent code that does not pass linter from being introduced to the project

## Next steps: 
- configure [Jest](http://jestjs.io) and [react-testing-library](https://github.com/kentcdodds/react-testing-library)
- investigate the feasibility of adding [Cypress](https://www.cypress.io/) to the project

### CODE REVIEW

**Comment by BenGamma** [comment]
Thanks for this PR @rudolphfunk, tests are something we want to implement since quite some times now !
Could you add a bit more informations on how the test would consist ?
Do we need to run a specific command ?
For now these commits seems related only to pre commit linting right ?

**Comment by rudolphfunk** [comment]
@BenGamma this PR only covers static code analysis running [TSLINT](https://palantir.github.io/tslint/) and [ESLINT](https://eslint.org/) and [Prettier](https://prettier.io/). Contributors should follow the usual workflow:

1.  Make their changes in their working copy (local repo)
2. Stage these changes once ready to commit `git add <path-to-file>/<filename>`
3. Commit their changes `git commit -m '<commitMessage>'`, upon which the precommit hook will trigger `lint-staged` to run the linters and formatter against the staged files.

The advantage of running these checks locally is that CI does not need to catch them, therefore shortening the feedback loop for developers.

> Could you add a bit more informations on how the test would consist ?
I think here you are referring to the unit or integration tests. I will get to these later and of course provide more guidance in the docs

> Do we need to run a specific command
No ( see steps above)

> For now these commits seems related only to pre commit linting right ?
Right you are

**Comment by rudolphfunk** [comment]
Reopening PR

**Comment by chrismclarke** [comment]
Hey, massively appreciate the effort and clear communication.

Could you rollback the default severity? This was quite a pain point in discussions a couple months back, summarised here: https://github.com/OneArmyWorld/onearmy/wiki/Typescript

**Comment by chrismclarke** [comment]
Also happy to see you're also looking at cypress, we had some discussions more widely here: https://github.com/OneArmyWorld/onearmy/issues/266

**Comment by rudolphfunk** [comment]
@chrismclarke, I have made the requested changes:

> In terms of linting I like the approach and agree, with request to rollback default severity.

Done

> I see there's also lots of changes to icons etc., please could you clarify, are these just to enforce the conventions specified? (i.e. no breaking changes)

This was prettier re-formatting my code. I had prettier disabled in my editor (settings from another project) and therefore the files were not formatted properly. I have reverted these changes to keep the PR clean. These files will get cleaned up in the future when changes are made and formatting rules are enforced.

**Comment by chrismclarke** [comment]
All sounds and looks great, thanks again (merged)

**Pull request merged**
