### PR TITLE
added svg icons, fonts, functional component rendering

### PR DESCRIPTION
**Pull request by charleenfei**
This PR covers just the initial styling for the How-To list component. (part of issue #234 )

features in this PR are: inclusion of the svg icons (placeholders for future functionality), font change, overall functional component rendering.

followup PR will include styling for the How-To content component.

### CODE REVIEW

**Comment by chrismclarke** [comment]
@BenGamma , do you think you can look at this tomorrow?

**Comment by chrismclarke** [comment]
(and also merge into master after as it's to the how-to branch - as an admin you can force the PR assuming all good here)

**Comment by chrismclarke** [comment]
Also if possible @charleenfei  when making a PR could you include a couple lines in the description just as a summary? The title and branch are pretty informative (clear that this is frontend style for how-to) but would also be nice to know whether there is still other things related to this in progress (less clear but would still be good to know), or if there is any discussions worth referencing in case the reviewer hasn't been following fully (e.g. save wondering why there's a new font by mentioning see #234). 

Thanks all the same though, appreciate the input!

**Comment by charleenfei** [comment]
> (and also merge into master after as it's to the how-to branch - as an admin you can force the PR assuming all good here)

this was done at @BenGamma 's request, he asked me to branch off the how-to module. What should I do?

**Comment by chrismclarke** [comment]
sorry that was more a reminder for @BenGamma , makes sense making the PR into this branch and then he can push everything to master together

**Comment by BenGamma** [comment]
Also @charleenfei I suggest you `git merge origin master` from your branch, as there were a lot of additions and potential breaking changes over the last week.
In case of too much conflicts I created a branch `charlee-howto-list-styling` with your current changes

**Comment by charleenfei** [comment]
> There was already an Icon component in `src/components/Icons`, which use the react-icons tiny library. I recommend you have a look at it and use this component to add new icons to avoid redundancy.
> 
> It may not be clear enough between if we are using material-ui or our own solution and I apologize for that.
> 
> To use a new icon : check the Icon you want in the list https://react-icons.netlify.com/#/icons/md
> Import it in the `Icons` component like `import { MdFileDownload } from 'react-icons/md'`
> Add a case for the imported icon to the `Glyph` const.
> Then you'll be able to use the new icon anywere in the project by importing the `Icons` component and use it like `<Icon glyph={'your-icon-name'} />`

Hey Ben, thanks for letting me know! The reason I create new Icon files was because the assets passed to me by @mattia-io were SVGs not found in the react-icons list that you have passed me. These are the icons specified by the design file. Let me know if I am misunderstanding something here!

**Comment by BenGamma** [comment]
Thanks @charleenfei, ok I see the point with Icons, we'll see with the design team how we manage this diversity of icons. That is a good first step in our own implementation of custom icons ✌️

**Pull request merged**
